<?php

$lines = file(dirname(__FILE__) . '/matroska-elements.txt');
print '$ids = [' . PHP_EOL;
foreach ($lines as $line)
{
        $fields = explode(' ', trim($line));
        $id = hexdec($fields[0]);
        $array['datatype'] = $fields[1];
        $array['name'] = $fields[2];
        $array['validParents'] = array();
        for ($i = 0; $i + 3 < count($fields); $i++)
        {
                if ($fields[$i + 3] == '*' || $fields[$i + 3] == 'root')
                {
                        $array['validParents'][$i] = $fields[$i + 3];
                }
                else
                {
                        $array['validParents'][$i] = hexdec($fields[$i + 3]);
                }
        }

        // IDS

        print "\t";
        print "'" . strtoupper($array['name']) . "' => " . $id . "," . PHP_EOL;


//        print "\t";
//        print $id . " => [" . PHP_EOL;
//        print "\t\t";
//        print "'datatype' => '" . $array['datatype'] . "'," . PHP_EOL;
//        print "\t\t";
//        print "'name' => '" . $array['name'] . "'," . PHP_EOL;
//        print "\t\t";
//        print "'validParents' => [" . PHP_EOL;
//        foreach ($array['validParents'] as $parent)
//        {
//                print "\t\t\t";
//                print $parent . "," . PHP_EOL;
//        }
//        print "\t\t";
//        print "]," . PHP_EOL;
//        print "\t";
//        print "]," . PHP_EOL;
}

print "];";


$ids = [
    'EBML' => 'a45dfa3',
    'EBMLVERSION' => '286',
    'EBMLREADVERSION' => '2f7',
    'EBMLMAXIDLENGTH' => '2f2',
    'EBMLMAXSIZELENGTH' => '2f3',
    'DOCTYPE' => '282',
    'DOCTYPEVERSION' => '287',
    'DOCTYPEREADVERSION' => '285',
    'VOID' => '6c',
    'CRC-32' => '3f',
    'SIGNATURESLOT' => 'b538667',
    'SIGNATUREALGO' => '3e8a',
    'SIGNATUREHASH' => '3e9a',
    'SIGNATUREPUBLICKEY' => '3ea5',
    'SIGNATURE' => '3eb5',
    'SIGNATUREELEMENTS' => '3e5b',
    'SIGNATUREELEMENTLIST' => '3e7b',
    'SIGNEDELEMENT' => '2532',
    'SEGMENT' => '8538067',
    'SEEKHEAD' => '14d9b74',
    'SEEK' => 'dbb',
    'SEEKID' => '13ab',
    'SEEKPOSITION' => '13ac',
    'INFO' => '549a966',
    'SEGMENTUID' => '33a4',
    'SEGMENTFILENAME' => '3384',
    'PREVUID' => '1cb923',
    'PREVFILENAME' => '1c83ab',
    'NEXTUID' => '1eb923',
    'NEXTFILENAME' => '1e83bb',
    'SEGMENTFAMILY' => '444',
    'CHAPTERTRANSLATE' => '2924',
    'CHAPTERTRANSLATEEDITIONUID' => '29fc',
    'CHAPTERTRANSLATECODEC' => '29bf',
    'CHAPTERTRANSLATEID' => '29a5',
    'TIMECODESCALE' => 'ad7b1',
    'DURATION' => '489',
    'DATEUTC' => '461',
    'TITLE' => '3ba9',
    'MUXINGAPP' => 'd80',
    'WRITINGAPP' => '1741',
    'CLUSTER' => 'f43b675',
    'TIMECODE' => '67',
    'SILENTTRACKS' => '1854',
    'SILENTTRACKNUMBER' => '18d7',
    'POSITION' => '27',
    'PREVSIZE' => '2b',
    'SIMPLEBLOCK' => '23',
    'BLOCKGROUP' => '20',
    'BLOCK' => '21',
    'BLOCKVIRTUAL' => '22',
    'BLOCKADDITIONS' => '35a1',
    'BLOCKMORE' => '26',
    'BLOCKADDID' => '6e',
    'BLOCKADDITIONAL' => '25',
    'BLOCKDURATION' => '1b',
    'REFERENCEPRIORITY' => '7a',
    'REFERENCEBLOCK' => '7b',
    'REFERENCEVIRTUAL' => '7d',
    'CODECSTATE' => '24',
    'DISCARDPADDING' => '35a2',
    'SLICES' => 'e',
    'TIMESLICE' => '68',
    'LACENUMBER' => '4c',
    'FRAMENUMBER' => '4d',
    'BLOCKADDITIONID' => '4b',
    'DELAY' => '4e',
    'SLICEDURATION' => '4f',
    'REFERENCEFRAME' => '48',
    'REFERENCEOFFSET' => '49',
    'REFERENCETIMECODE' => '4a',
    'ENCRYPTEDBLOCK' => '2f',
    'TRACKS' => '654ae6b',
    'TRACKENTRY' => '2e',
    'TRACKNUMBER' => '57',
    'TRACKUID' => '33c5',
    'TRACKTYPE' => '3',
    'FLAGENABLED' => '39',
    'FLAGDEFAULT' => '8',
    'FLAGFORCED' => '15aa',
    'FLAGLACING' => '1c',
    'MINCACHE' => '2de7',
    'MAXCACHE' => '2df8',
    'DEFAULTDURATION' => '3e383',
    'DEFAULTDECODEDFIELDDURATION' => '34e7a',
    'TRACKTIMECODESCALE' => '3314f',
    'TRACKOFFSET' => '137f',
    'MAXBLOCKADDITIONID' => '15ee',
    'NAME' => '136e',
    'LANGUAGE' => '2b59c',
    'CODECID' => '6',
    'CODECPRIVATE' => '23a2',
    'CODECNAME' => '58688',
    'ATTACHMENTLINK' => '3446',
    'CODECSETTINGS' => '1a9697',
    'CODECINFOURL' => '1b4040',
    'CODECDOWNLOADURL' => '6b240',
    'CODECDECODEALL' => '2a',
    'TRACKOVERLAY' => '2fab',
    'CODECDELAY' => '16aa',
    'SEEKPREROLL' => '16bb',
    'TRACKTRANSLATE' => '2624',
    'TRACKTRANSLATEEDITIONUID' => '26fc',
    'TRACKTRANSLATECODEC' => '26bf',
    'TRACKTRANSLATETRACKID' => '26a5',
    'VIDEO' => '60',
    'FLAGINTERLACED' => '1a',
    'STEREOMODE' => '13b8',
    'ALPHAMODE' => '13c0',
    'OLDSTEREOMODE' => '13b9',
    'PIXELWIDTH' => '30',
    'PIXELHEIGHT' => '3a',
    'PIXELCROPBOTTOM' => '14aa',
    'PIXELCROPTOP' => '14bb',
    'PIXELCROPLEFT' => '14cc',
    'PIXELCROPRIGHT' => '14dd',
    'DISPLAYWIDTH' => '14b0',
    'DISPLAYHEIGHT' => '14ba',
    'DISPLAYUNIT' => '14b2',
    'ASPECTRATIOTYPE' => '14b3',
    'COLOURSPACE' => 'eb524',
    'GAMMAVALUE' => 'fb523',
    'FRAMERATE' => '383e3',
    'AUDIO' => '61',
    'SAMPLINGFREQUENCY' => '35',
    'OUTPUTSAMPLINGFREQUENCY' => '38b5',
    'CHANNELS' => '1f',
    'CHANNELPOSITIONS' => '3d7b',
    'BITDEPTH' => '2264',
    'TRACKOPERATION' => '62',
    'TRACKCOMBINEPLANES' => '63',
    'TRACKPLANE' => '64',
    'TRACKPLANEUID' => '65',
    'TRACKPLANETYPE' => '66',
    'TRACKJOINBLOCKS' => '69',
    'TRACKJOINUID' => '6d',
    'TRICKTRACKUID' => '40',
    'TRICKTRACKSEGMENTUID' => '41',
    'TRICKTRACKFLAG' => '46',
    'TRICKMASTERTRACKUID' => '47',
    'TRICKMASTERTRACKSEGMENTUID' => '44',
    'CONTENTENCODINGS' => '2d80',
    'CONTENTENCODING' => '2240',
    'CONTENTENCODINGORDER' => '1031',
    'CONTENTENCODINGSCOPE' => '1032',
    'CONTENTENCODINGTYPE' => '1033',
    'CONTENTCOMPRESSION' => '1034',
    'CONTENTCOMPALGO' => '254',
    'CONTENTCOMPSETTINGS' => '255',
    'CONTENTENCRYPTION' => '1035',
    'CONTENTENCALGO' => '7e1',
    'CONTENTENCKEYID' => '7e2',
    'CONTENTSIGNATURE' => '7e3',
    'CONTENTSIGKEYID' => '7e4',
    'CONTENTSIGALGO' => '7e5',
    'CONTENTSIGHASHALGO' => '7e6',
    'CUES' => 'c53bb6b',
    'CUEPOINT' => '3b',
    'CUETIME' => '33',
    'CUETRACKPOSITIONS' => '37',
    'CUETRACK' => '77',
    'CUECLUSTERPOSITION' => '71',
    'CUERELATIVEPOSITION' => '70',
    'CUEDURATION' => '32',
    'CUEBLOCKNUMBER' => '1378',
    'CUECODECSTATE' => '6a',
    'CUEREFERENCE' => '5b',
    'CUEREFTIME' => '16',
    'CUEREFCLUSTER' => '17',
    'CUEREFNUMBER' => '135f',
    'CUEREFCODECSTATE' => '6b',
    'ATTACHMENTS' => '941a469',
    'ATTACHEDFILE' => '21a7',
    'FILEDESCRIPTION' => '67e',
    'FILENAME' => '66e',
    'FILEMIMETYPE' => '660',
    'FILEDATA' => '65c',
    'FILEUID' => '6ae',
    'FILEREFERRAL' => '675',
    'FILEUSEDSTARTTIME' => '661',
    'FILEUSEDENDTIME' => '662',
    'CHAPTERS' => '43a770',
    'EDITIONENTRY' => '5b9',
    'EDITIONUID' => '5bc',
    'EDITIONFLAGHIDDEN' => '5bd',
    'EDITIONFLAGDEFAULT' => '5db',
    'EDITIONFLAGORDERED' => '5dd',
    'CHAPTERATOM' => '36',
    'CHAPTERUID' => '33c4',
    'CHAPTERSTRINGUID' => '1654',
    'CHAPTERTIMESTART' => '11',
    'CHAPTERTIMEEND' => '12',
    'CHAPTERFLAGHIDDEN' => '18',
    'CHAPTERFLAGENABLED' => '598',
    'CHAPTERSEGMENTUID' => '2e67',
    'CHAPTERSEGMENTEDITIONUID' => '2ebc',
    'CHAPTERPHYSICALEQUIV' => '23c3',
    'CHAPTERTRACK' => 'f',
    'CHAPTERTRACKNUMBER' => '9',
    'CHAPTERDISPLAY' => '0',
    'CHAPSTRING' => '5',
    'CHAPLANGUAGE' => '37c',
    'CHAPCOUNTRY' => '37e',
    'CHAPPROCESS' => '2944',
    'CHAPPROCESSCODECID' => '2955',
    'CHAPPROCESSPRIVATE' => '50d',
    'CHAPPROCESSCOMMAND' => '2911',
    'CHAPPROCESSTIME' => '2922',
    'CHAPPROCESSDATA' => '2933',
    'TAGS' => '254c367',
    'TAG' => '3373',
    'TARGETS' => '23c0',
    'TARGETTYPEVALUE' => '28ca',
    'TARGETTYPE' => '23ca',
    'TAGTRACKUID' => '23c5',
    'TAGEDITIONUID' => '23c9',
    'TAGCHAPTERUID' => '23c4',
    'TAGATTACHMENTUID' => '23c6',
    'SIMPLETAG' => '27c8',
    'TAGNAME' => '5a3',
    'TAGLANGUAGE' => '47a',
    'TAGDEFAULT' => '484',
    'TAGSTRING' => '487',
    'TAGBINARY' => '485',
];
